### PR TITLE
Issue #8 Dashboard page

### PR DESCRIPTION
**Pull request by SachinMhetre678**
## 1. Authentication System
- **Admin Login Page:**
  - Added a custom login form with fields for username and password.
  - Implemented error handling for invalid credentials.
  - Mock authentication setup (username: `admin`, password: `********`).
  - Secure routing with protected routes.
  - Session management using `localStorage` for storing authentication state.

## 2. Protected Routes
- **Route Protection:**
  - Implemented authentication state checking to restrict access to protected routes.
  - Unauthorized users are automatically redirected to the login page.
  - Protected routes include the admin dashboard and team creation sections.

## 3. Admin Dashboard
- **Team Management:**
  - Designed a table view for all teams with real-time search functionality.
  - Enabled editing of team details:
    - Team name.
    - Challenge scores (1-3).
    - Completion time.
    - Total points automatically calculated based on scores.
  - Added delete functionality to remove teams.
  - Provided the option to create new teams directly from the dashboard.

## 4. Team Creation
- **Create Team Form:**
  - Developed a form to create new teams with the following features:
    - Input for team name.
    - Automatic ID generation for each team.
    - Initial state setup with zero points for all challenges and a default completion time of `0:00:00`.
    - Form validation to ensure correct inputs.
    - Redirect to the appropriate page after successful team creation.

## 5. Leaderboard Features
- **Live Updates:**
  - Integrated real-time score updates with automatic sorting based on total points.
  - Implemented a 5-second refresh interval for dynamic leaderboard updates.
  - Animated transitions for smoother updates.
  - Designed a responsive layout with highlighted top 3 teams, rank icons, and avatars.

## 6. Data Management
- **Local Storage:**
  - Used `localStorage` to ensure persistent data storage for teams.
  - Data structure includes:
    - Unique ID.
    - Team name.
    - Individual challenge scores.
    - Total points.
    - Completion time.
  - Real-time updates to data on edit or create operations.
  - Added validation to ensure the integrity of stored data.

## 7. Navigation
- **Routing System:**
  - Configured routing for:
    - Home page.
    - Events page.
    - Admin dashboard.
    - Leaderboard.
    - Team creation.
  - Ensured protected routes for sensitive sections of the application.

image
image
image
image

### CODE REVIEW

**Review by onkar69483 — APPROVED** [review]
looks great

**Review by PranavGitHubAcc — APPROVED** [review]
Changes Approved

**Comment by PranavGitHubAcc** [comment]
Closes #6 
Closes #7 
Closes #8

**Comment by PranavGitHubAcc** [comment]
Further changes in new issues.
Search bar for Leaderboard page.
Add Avatar (Emoji) to Team model.
Frontend-Backend integration for leaderboard.
Location and timing detail on Landing page under join the battle.
Remove Register Team and View Schedule. 
Fix Live Leaderboard on Landing page

**Pull request merged**
